{
 "title": "RDB_Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Main database info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database_attachments",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "database_attachments{job=\"rdb_exporter\"}"
    }
   ]
  },
  {
   "title": "Database_size_MB",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "database_size{job=\"rdb_exporter\"}"
    }
   ]
  },
  { "title": "GSTAT INFO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "OAT_OIT_difference",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(gstat_OAT_OIT_difference{job=\"rdb_exporter\"}[$__interval])"
    }
   ]
  },
  {
   "title": "NT_OIT_difference",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "gstat_NT_OIT_difference{job=\"rdb_exporter\"}"
    }
   ]
  },
  {
   "title": "Firebird log Errors today",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Firebird_Err_consistency{job=\"rdb_exporter\"}",
     "legendFormat": "Consistancy Check"
    },
    {
     "expr": "Firebird_Err_read{job=\"rdb_exporter\"}",
     "legendFormat": "Reading from file errors"
    },
    {
     "expr": "Firebird_Err_write{job=\"rdb_exporter\"}",
     "legendFormat": "Writing to file errors"
    }
   ]
  }
 ]
}